---
- name: install nginx
  apt: name=nginx state=present
- name: update config line
  replace: dest=/etc/nginx/sites-available/default regexp='(index)\.index' replace='\1\.php'
  notify:
    - restart nginx
  
