---
- name: Download Kibana
  command: cd ~; wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz

- name: Extract Kibana archive
  command: tar xvf kibana-*.tar.gz


# make it so Kibana will only be accessible to the localhost
# vi ~/kibana-4*/config/kibana.yml
# host: "localhost"

- name: Create install location for Kibana
  command: sudo mkdir -p /opt/kibana

- name: Install Kibana in /opt
  command: sudo cp -R ~/kibana-4*/* /opt/kibana/

- name: Download and install Kibana init script
  command: cd /etc/init.d && sudo wget https://gist.githubusercontent.com/thisismitch/8b15ac909aed214ad04a/raw/bce61d85643c2dcdfbc2728c55a41dab444dca20/kibana4

- name: Enable Kibana service
  command: sudo chmod +x /etc/init.d/kibana4 && sudo update-rc.d kibana4 defaults 96 9

- name: Start Kibana
  service: name=kibana4 state=start

