---
- name: create md raid device
  shell: "mdadm --create /dev/md0 --level=0 --raid-devices=3 /dev/sdb /dev/sdc /dev/sdd"
- name: format the filesystem
  filesystem: fstype=ext4 dev=/dev/md0
- name: label the drive
  shell: e2label /dev/md0 data
- name: mount new filesystem
  mount: name=/data src='LABEL=data' fstype=ext4 opts=rw state=mounted