---
- name: Add Oracle Java aptitude repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Install Java 8
  apt: pkg=oracle-java8-installer state=installed update_cache=yes
  
