---
- name: import ElasticSearch public key
  command: wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Create ElasticSearch source list
  command: echo 'deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' | sudo tee /etc/apt/sources.list.d/elasticsearch.list

- name: Install ElasticSearch
  apt: name=elasticsearch=1.4.4 update_cache=yes

## TODO: Edit /etc/elasticsearch/elasticsearch.yml to restrict outside access to port 9200
## network.host: localhost

- name: Restart ElasticSearch
  service: name=elasticsearch state=restart

- name: Set ElasticSearch to start on boot
  command: sudo update-rc.d elasticsearch defaults 95 10

